language: java
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  app:
    master: "citest-uf46619"
  api_key:
    secure: "g5Dvg+Ry/ZQJMB3a9+SkvWsj8yLuXpy/v9GffxQCPyaIgMDWUzn+j/AZwNqEPhsRskENlaaJz42w9+6pvLFTmSRgVqDeI8biXrlBXzfO91lITBaEBbUoVFsIECPMZzjQJJ21erfoWUHWdPn7dcPhxu2n86GFUAMDrH+qWl8Ro10/TsSv+a+gxas7AJgOeiUOxcBZs34LRwxxgrgQyTeEmpcVIK4h/X5RPYZoYS81lTEJ3oepDSE+86ODnZzMuh4tB/jIFN4xDE4bkUswwnJSoJR/WsZs73UNP6ri/SO5zVB5ZXQoC7Po4Fa9T7lE7SvfYYa/ACBorKX9kwKqdGIhcjNZPcHKaBv0KXM8+P9oZ9Q4yt0F9iZZM4b07UEdOEKH42ox6KxJghKeE/3VIwBL9B1Fo2MCsUyr1nonQbv6Z07CoZdnBOUAeJkVKJLd+4zXmY499tr1NvxKJ9MtaLKwf2uTONOpv74owwpgw30JVBAOXeuFj73mIgWaIlwYRIwKDsMKT+LDazqiZeyAVlDA8hISRhjOI+FHrlWjkR2OXMwKPqBbgBYbVlXxB+Ce4T8mQERMwzwmoQVETdmsU3VyZs671IBkAcxov/+SggIs3XwMZhEk9rtiQEHfT+6Gijyigxa5r42rDWP4IfB6wYYGEjDOJtzcx+sqXzAEPp04Wt8="
#  on:
#    branch: master